---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by digitsu.
--- DateTime: 2021/12/06 12:27
--- This frobot is an interface test jig
---
--- dummy frobot sits there until damaged, when he will run away in a random direction at half speed, until he hits an obstacle

return function(state, ...)
    state = state or {}
    state.type = "dummy"
    if state.damage == nil then
        state.panic_counter = -1
        state.damage = damage()
    elseif state.damage ~= damage() then
        state.damage = damage() --- don't forget to reset the damage stat!
        state.course = math.random(359)
        drive(state.course, 50)
        state.status = "panic!"
        state.panic_counter = 10
    elseif state.panic_counter < 0 then
        state.panic_counter = -1
        drive(0,0)
        state.status = "calm"
    else
        state.course = math.random(359)
        drive(state.course, 50)
        state.panic_counter = state.panic_counter -1
    end
    return state
end